services:
    rust:
        build: .
        volumes:
            - ./app:/app
        working_dir: /app
        environment:
            USER: "user"
            DATABASE_URL: "postgres://loco:loco@postgres:5432/loco_app"
        tty: true
    postgres:
        image: postgres:latest
        restart: always
        ports:
            - "5432:5432"
        volumes:
            - ./data:/var/lib/postgresql/data
        environment:
            POSTGRES_USER: "loco"
            POSTGRES_DB: "loco_app"
            POSTGRES_PASSWORD: "loco"
    redis:
        image: "redis:latest"
        ports:
            - "6379:6379"
        volumes:
            - "./redis/redis:/data"
